# tests/lib.sh -- shared helpers for the bash-gitaware test suite.
#
# Sourced by run.sh; scenarios.sh and perf.sh use the helpers defined here.
# shellcheck shell=bash

# Project root (absolute). Computed from this file's location.
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Test counters.
_passed=0
_failed=0
_skipped=0
_failures=()

ok()      { _passed=$(( _passed + 1 )); printf '  OK   %s\n' "$1"; }
fail()    { _failed=$(( _failed + 1 )); _failures+=("$1"); printf '  FAIL %s\n' "$1"; }
skip()    { _skipped=$(( _skipped + 1 )); printf '  SKIP %s\n' "$1"; }
section() { printf '\n== %s ==\n' "$1"; }

# Assert a substring is present in $1.
#   assert_contains "<haystack>" "<needle>" "<label>"
assert_contains() {
    local haystack="$1" needle="$2" label="$3"
    case "$haystack" in
        *"$needle"*) ok "$label: contains $(printf '%q' "$needle")" ;;
        *) fail "$label: missing $(printf '%q' "$needle") (got: $(printf '%q' "$haystack"))" ;;
    esac
}

# Assert a substring is absent in $1.
assert_lacks() {
    local haystack="$1" needle="$2" label="$3"
    case "$haystack" in
        *"$needle"*) fail "$label: should NOT contain $(printf '%q' "$needle") (got: $(printf '%q' "$haystack"))" ;;
        *) ok "$label: lacks $(printf '%q' "$needle")" ;;
    esac
}

# Create a fresh empty git repo in a temp dir. Echoes the dir path.
mktemp_repo() {
    local d; d="$(mktemp -d "${TMPDIR:-/tmp}/bga-test-XXXXXX")"
    git -C "$d" init -q -b main
    git -C "$d" config user.email test@example.com
    git -C "$d" config user.name "BGA Test"
    printf '%s' "$d"
}

# Render bash-gitaware's PS1 in $1 with optional env vars. Stdout is the
# expanded PS1 (with ANSI escapes preserved). Stderr is silenced.
#   bga_render <dir> [VAR=val ...]
#
# Note: defaults BASHGITAWARE_ASYNC=0 unless the caller sets it explicitly.
# Async is a "deferred refresh on the next prompt" path (see ADR-0005); a
# single-render call returns the cheap-only snapshot, which is correct for
# the async-specific tests but defeats the assertions of the sync scenarios
# (dirty marker, ahead/behind counters, ...). Async-specific tests pass
# "BASHGITAWARE_ASYNC=1" explicitly.
bga_render() {
    local dir="$1"; shift
    local kv prelude="" has_async=0
    for kv in "$@"; do
        case "$kv" in BASHGITAWARE_ASYNC=*) has_async=1 ;; esac
        prelude+="export $kv; "
    done
    [ "$has_async" = 0 ] && prelude="export BASHGITAWARE_ASYNC=0; $prelude"
    bash --norc --noprofile -i -c "
        export HOME='$HOME' PATH='$PATH' TERM='xterm-256color' LANG='C.UTF-8' COLUMNS=120
        $prelude
        cd '$dir' 2>/dev/null
        source '$REPO/new.bashrc'
        __bga_prompt
        printf '%s' \"\${PS1@P}\"
    " 2>/dev/null
}

# Sanity test that we can lint each lib/ module on its own (syntax check).
lib_syntax_check() {
    section "lib/ module syntax"
    local f
    for f in "$REPO"/lib/[0-9][0-9]-*.bash; do
        if bash -n "$f" 2>/dev/null; then
            ok "syntax: $(basename "$f")"
        else
            fail "syntax: $(basename "$f")"
        fi
    done
}

# Verify new.bashrc is up to date with lib/.
build_freshness_check() {
    section "build freshness"
    local tmp; tmp="$(mktemp)"
    if bash "$REPO/bin/build.sh" >/dev/null 2>&1 && diff -q "$tmp" "$REPO/new.bashrc" >/dev/null 2>&1; then
        ok "new.bashrc matches build output"
    elif [ -f "$REPO/new.bashrc" ]; then
        # Re-run build into a tmp file directly for a more accurate check.
        local out_tmp; out_tmp="$(mktemp)"
        {
            # shellcheck disable=SC2016
            printf '%s\n' '# Generated by bin/build.sh -- do not edit. Edit lib/*.bash and run `make build`.'
            printf '%s\n' '# shellcheck shell=bash'
            cat "$REPO"/lib/[0-9][0-9]-*.bash
        } > "$out_tmp"
        if diff -q "$out_tmp" "$REPO/new.bashrc" >/dev/null 2>&1; then
            ok "new.bashrc matches build output"
        else
            fail "new.bashrc out of date -- run 'make build' and commit"
        fi
        rm -f "$out_tmp"
    fi
    rm -f "$tmp"
}
